export const indiaStates = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

export const indiaDistrictsByState = {
  'Andhra Pradesh': ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna', 'Kurnool', 'Nellore', 'Prakasam', 'Srikakulam', 'Visakhapatnam', 'Vizianagaram', 'West Godavari'],
  'Arunachal Pradesh': ['Itanagar Capital Complex', 'East Siang', 'Lower Subansiri', 'Papum Pare', 'Tawang', 'West Kameng'],
  Assam: ['Baksa', 'Barpeta', 'Cachar', 'Dibrugarh', 'Goalpara', 'Golaghat', 'Kamrup Metropolitan', 'Karimganj', 'Nagaon', 'Sivasagar', 'Sonitpur', 'Tinsukia'],
  Bihar: ['Araria', 'Bhagalpur', 'Darbhanga', 'Gaya', 'Muzaffarpur', 'Nalanda', 'Patna', 'Purnia', 'Rohtas', 'Saran'],
  Chandigarh: ['Chandigarh'],
  Chhattisgarh: ['Balod', 'Bilaspur', 'Durg', 'Janjgir-Champa', 'Korba', 'Raigarh', 'Raipur', 'Rajnandgaon'],
  Delhi: ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'North East Delhi', 'North West Delhi', 'Shahdara', 'South Delhi', 'South East Delhi', 'South West Delhi', 'West Delhi'],
  Goa: ['North Goa', 'South Goa'],
  Gujarat: ['Ahmedabad', 'Amreli', 'Anand', 'Banaskantha', 'Bhavnagar', 'Gandhinagar', 'Jamnagar', 'Junagadh', 'Kutch', 'Rajkot', 'Surat', 'Vadodara'],
  Haryana: ['Ambala', 'Faridabad', 'Gurugram', 'Hisar', 'Karnal', 'Kurukshetra', 'Panipat', 'Rohtak', 'Sonipat'],
  'Himachal Pradesh': ['Bilaspur', 'Chamba', 'Hamirpur', 'Kangra', 'Kullu', 'Mandi', 'Shimla', 'Solan'],
  'Jammu and Kashmir': ['Anantnag', 'Baramulla', 'Doda', 'Jammu', 'Kathua', 'Pulwama', 'Srinagar', 'Udhampur'],
  Jharkhand: ['Bokaro', 'Deoghar', 'Dhanbad', 'East Singhbhum', 'Hazaribagh', 'Ranchi', 'West Singhbhum'],
  Karnataka: ['Bagalkot', 'Ballari', 'Bengaluru Rural', 'Bengaluru Urban', 'Belagavi', 'Dakshina Kannada', 'Dharwad', 'Kalaburagi', 'Mysuru', 'Shivamogga', 'Tumakuru', 'Udupi'],
  Kerala: ['Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Thiruvananthapuram', 'Thrissur'],
  Ladakh: ['Kargil', 'Leh'],
  Lakshadweep: ['Lakshadweep'],
  'Madhya Pradesh': ['Bhopal', 'Gwalior', 'Indore', 'Jabalpur', 'Rewa', 'Sagar', 'Satna', 'Ujjain'],
  Maharashtra: ['Ahmednagar', 'Aurangabad', 'Kolhapur', 'Mumbai', 'Nagpur', 'Nashik', 'Pune', 'Raigad', 'Solapur', 'Thane'],
  Manipur: ['Bishnupur', 'Churachandpur', 'Imphal East', 'Imphal West', 'Thoubal'],
  Meghalaya: ['East Khasi Hills', 'Ri Bhoi', 'South West Garo Hills', 'West Garo Hills', 'West Jaintia Hills'],
  Mizoram: ['Aizawl', 'Champhai', 'Kolasib', 'Lunglei', 'Serchhip'],
  Nagaland: ['Dimapur', 'Kohima', 'Mokokchung', 'Mon', 'Tuensang'],
  Odisha: ['Balasore', 'Cuttack', 'Ganjam', 'Khordha', 'Mayurbhanj', 'Puri', 'Sambalpur', 'Sundargarh'],
  Puducherry: ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
  Punjab: ['Amritsar', 'Bathinda', 'Jalandhar', 'Ludhiana', 'Patiala', 'Sangrur'],
  Rajasthan: ['Ajmer', 'Alwar', 'Bikaner', 'Jaipur', 'Jodhpur', 'Kota', 'Udaipur'],
  Sikkim: ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Thanjavur', 'Tiruchirappalli', 'Tirunelveli', 'Vellore'],
  Telangana: ['Adilabad', 'Hyderabad', 'Karimnagar', 'Khammam', 'Medchal Malkajgiri', 'Nalgonda', 'Nizamabad', 'Rangareddy', 'Warangal Urban'],
  Tripura: ['Dhalai', 'Gomati', 'North Tripura', 'South Tripura', 'West Tripura'],
  'Uttar Pradesh': ['Agra', 'Aligarh', 'Gautam Buddha Nagar', 'Ghaziabad', 'Kanpur Nagar', 'Lucknow', 'Meerut', 'Prayagraj', 'Varanasi'],
  Uttarakhand: ['Almora', 'Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Udham Singh Nagar'],
  'West Bengal': ['Darjeeling', 'Hooghly', 'Howrah', 'Kolkata', 'Murshidabad', 'Nadia', 'North 24 Parganas', 'Paschim Bardhaman', 'South 24 Parganas'],
  'Andaman and Nicobar Islands': ['Nicobar', 'North and Middle Andaman', 'South Andaman'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Dadra and Nagar Haveli', 'Daman', 'Diu'],
};
